# Generated by Django 2.2 on 2021-08-09 18:52

from django.db import migrations, models
import django.db.models.deletion
import event_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, validators=[event_app.models.name_validator])),
                ('last_name', models.CharField(max_length=255, validators=[event_app.models.name_validator])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255, validators=[event_app.models.password_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[event_app.models.title_validator])),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255, validators=[event_app.models.address_validator])),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('attendees', models.ManyToManyField(null=True, related_name='events_attended', to='event_app.User')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_hosted', to='event_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, validators=[event_app.models.comment_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_made', to='event_app.User')),
                ('event_commented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='event_app.Event')),
            ],
        ),
    ]
