# Generated by Django 2.2 on 2021-08-12 18:43

from django.db import migrations, models
import event_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_auto_20210809_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=255, validators=[event_app.models.description_validator]),
        ),
    ]
